# Generated by Django 6.0.6 on 2026-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_emotions', models.JSONField(default=dict)),
                ('wife_emotions', models.JSONField(default=dict)),
                ('conflict_type', models.CharField(max_length=100)),
                ('root_cause', models.TextField()),
                ('resolution', models.TextField()),
                ('communication_script', models.TextField()),
                ('is_escalated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_ai', models.BooleanField(default=False)),
                ('phase', models.CharField(choices=[('individual', 'Individual'), ('cross_ref', 'Cross Reference'), ('clarification', 'Clarification')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('waiting', 'Waiting')], default='sent', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConflictSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('cross_referencing', 'Cross Referencing'), ('analyzing', 'Analyzing'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='collecting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('partial', 'Partially Resolved'), ('no', 'Not Yet')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('milestone', models.CharField(max_length=200)),
            ],
        ),
    ]
