# Generated by Django 6.0.6 on 2026-06-29 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conflicts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflictsession',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_sessions', to='users.coupleprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conflicts.conflictsession'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='conflicts.conflictsession'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='conflicts.conflictsession'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='conflicts.conflictsession'),
        ),
    ]
