# Generated by Django 6.0.6 on 2026-07-01 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflicts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='severity',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='visible_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflictsession',
            name='mismatch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='phase',
            field=models.CharField(choices=[('individual', 'Individual'), ('cross_ref', 'Cross Reference'), ('clarification', 'Clarification'), ('advice', 'Advice'), ('escalation', 'Escalation')], max_length=20),
        ),
    ]
